- src/css/adoc/table.css
Added css properties to our table's style so that we can use the asciidoc table alignment properties in our content.
@mojavelinux I would think these style declarations can be made simpler? Or do I need to specifically declare each alignment as I did here? 
I tested against a local UI bundle and the results are the expected ones:
<.< aligns to left and top
<.^ aligns to left and center
<.> aligns to left and bottom
^.< aligns to middle and top
^.^ aligns to middle and center
^.> aligns to middle and bottom
\>.< aligns to right and top
\>.^ aligns to right and center
\>.> aligns to right and bottom
This change also makes our default alignment to be **<.< (aligns to left and top)**
> DOCSINFRA-141 Add alignment properties to the tables

- src/css/adoc/doc.css
- src/css/globals/grid.css
- src/css/globals/utility.css
- src/css/globals/vars.css
- src/css/specific/header.css
- src/css/vendor/coveo.css
- src/partials/search.hbs
https://www.mulesoft.org/jira/browse/DOCSINFRA-118
Changes:
* Adds an additional max-width for larger screens (up to 1650px)
* Adds a blurb about version facets
* Fixes anchor icon alignment in headings
> DOCSINFRA-155 Resolve feedback & fix anchor alignment

- src/partials/footer.hbs
After the updates made in the header and footer, this PR removes the unnecessary GDPR banner from the docs site.
> Remove unnecesay GDPR banner

- src/helpers/connectors.js
Partial builds that include connectors fail with the error:
Cannot read property 'attributes' of undefined in UI template partials/connectors-table.hbs
The issue is that when the components are imported from the primary site, those components do not include the asciidoc property from the component descriptor. The template was assuming this property is always set.  This introduces a fallback.
> Tweak the connectors helper to allow partial builds

- src/partials/connectors/connectors-sidebar.hbs
missing the TOC survey from the connectors page. I am adding it back
> add survey toc to connectors

- src/partials/connectors/connectors-sidebar.hbs
ref: [W-10592784](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000laYdNYAU/view)
In the sidebar of connector pages (e.g. https://docs.mulesoft.com/amazon-kinesis-connector/1.0/), add a link to the level value. It's the same link for all support levels (select or premium).
To test, run `gulp preview` in this branch, then navigate to http://localhost:5252/connector.html and click "Select" in the sidebar. Doing so will open the [support policy page|https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors] *in a new tab*.
> [W-10592784] add link to connector support level

- .github/CODEOWNERS
- src/css/specific/toolbar.css
ref: W-10592990
- unhide breadcrumbs from bigger screens. Previously there were only visible in small screens.
- add docsinfra as codeowners
> [W-10592990] unhide breadcrumbs

- src/css/components/survey.css
- src/partials/survey-toc.hbs
ref: [W-11071630](https://gus.my.salesforce.com/a07EE00000vxGusYAE)
- remove `type="button"` from survey TOC element. It was breaking the element appearance in Safari
- slight adjustments on the survey element CSS so it looks better on Safari
These screenshots are taken from Safari. The layouts are not perfect but we can fix them later.
> [W-11071630] adjust survey TOC CSS for Safari

- src/css/vendor/coveo.css
- src/partials/search.hbs
ref: [W-10592497](https://gus.lightning.force.com/a07EE00000laXUbYAM)
The search modal's close "button" used to have only a svg tag. I have wrapped it within a proper button tag so that it is an actual button. The button is borderless and has a very light gray background color that is visible in all major browsers (Chrome, Safari, Firefox) to make it look like a real button, but not dark enough to hide the X icon. Moreover, hovering on the button will show the tooltip text "Close", further clarifying what the button does (but this can be reworded as "Close search", "Close window" and others). 
When not hovered
When hovered
> [W-10592497] add button to close modal

- src/layouts/404.hbs
- src/layouts/connectors-home.hbs
- src/layouts/default.hbs
- src/layouts/rtfcloud-home.hbs
ref: W-11173514
note: to use this UI bundle, you will have to add this to the antora playbook:
```yaml
site:
keys:
site_profile: prod
```
add a `noindex` meta tag to all pages that are not prod or jp, based on https://developers.google.com/search/docs/advanced/crawling/block-indexing which is the recommended way to tell web crawlers to not index pages. Traditionally, robots.txt was used to block crawlers from the beta pages, but according to [Google](https://developers.google.com/search/docs/advanced/robots/intro#understand-the-limitations-of-a-robots.txt-file):
> **A page that's disallowed in robots.txt can still be indexed if linked to from other sites.**
While Google won't crawl or index the content blocked by a robots.txt file, we might still find and index a disallowed URL if it is …
> [W-11173514] adding noindex meta tag

- preview-site-src/element-examples.adoc
- src/js/09-external-links.js
ref: [W-10592545](https://gus.lightning.force.com/a07EE00000laXVNYA2)
add "alt text" to the external link icon. See https://stackoverflow.com/questions/4216035/css-background-image-alt-attribute why it is done in JS instead of CSS. _tl;dr you can't add the alt attribute in CSS, and alt doesn't apply to <a> elements, but title does the same thing._
use `gulp preview` and go to http://localhost:5252/element-examples.html#_url. There is an external link there, hover on it and it should display "leaving the site". You can do the same for the salesforce icon at the top.
> [W-10592545] alt text for external links

- src/css/globals/typography.css
- src/css/specific/navigation.css
- src/css/specific/toc.css
ref: W-10592499
**Note that this does not solve the main issue in the GUS ticket, but it's a good place to start. Only test this in Google Chrome as it is not yet compatible with Safari and Firefox.**
Currently in Chrome, the left TOC menu items are tab-able, but they do not have an outline so from an accessibility's perspective, it's hard to see which tab is the current focus. For example, if you go to https://docs.mulesoft.com/ right now and keep pressing the tab key to reach the TOC menu, you will see on the lower left corner that the browser is focusing on the menu items with different URLs, but there's nothing in the UI showing the focus.
This PR removes the `outline: 0` attributes from CSS to make the outlines show again:
To test, please run `gulp preview`, open …
> [W-10592499] make toc tab outline show in Chrome

- src/css/adoc/doc.css
ref: [W-10592950](https://gus.lightning.force.com/a07EE00000laaDDYAY)
allow ordered lists to use a different numbering or lettering scheme (e.g., arabic, alpha, roman, etc) instead of only numbers.
run `gulp preview` and open http://localhost:5252/element-examples.html#_list to validate that the numbers are displayed in different format based on the heading (roman, arabic, greek), instead of all arabic numbers.
> [W-10592950] fix ol styles

- preview-site-src/ui-model.yml
- src/css/specific/header.css
- src/helpers/isNull.js
- src/partials/connectors/connectors-table.hbs
ref: [W-11256404](https://gus.lightning.force.com/a07EE00000yeGGmYAM)
make the connector icon extensions parameterized by a new page attribute named **page-icon-extension**. This allows each connector to specify in antora.yml what the extension is, for example png. If the attribute is omitted, the default extension is svg.
I added an amazon-sns-connector in the gulp preview site to demonstrate that it works. Its icon is in the png format, so on http://localhost:5252/connectors.html, all 4 icons (the other 3 are svg's) should display properly.
Also added a helper function, `isNull`, to help determine if an attribute is supplied or not.
> [W-11256404] parameterize connector icon extension

- src/css/specific/toc.css
- src/js/01-nav.js
- src/js/10-notice-banner.js
ref: [W-11477491](https://gus.lightning.force.com/a07EE0000124xj4YAA)
fix the following bugs:
- submenu dropdown is too long, which expands the screen too wide
- when clicking on the left nav version pill, the version list is hidden behind the left nav
- console errors are seen when page doesn't have the deprecation banner (happens in all screen sizes)
https://www.loom.com/share/c8182746ca7a4535b567f9555c95ed10
> [W-11477491] mobile bugs

- src/js/01-nav.js
ref: W-11487023
add a function to fix a bug where on mobile, after touching/tapping on 1 version and then another version, the dropdown menu for the first version is never hidden.
https://www.loom.com/share/8ee6bdaca6b9470190936192df97cd6c
> [W-11487023] add hideExistingVersions

- src/partials/notice-banner.hbs
ref: [W-11489300](https://gus.lightning.force.com/a07EE000012EtNQYA0)
fix a bug where in the yellow notice banner, the "latest version" link is not routing to the correct version.
https://www.loom.com/share/44926718a729464c970b876f075b8ee6
> [W-11489300 ] fix syntax

- src/css/specific/nav.css
ref: [W-11541098](https://gus.lightning.force.com/a07EE000013CbMeYAK)
fix a bug where search box does not stick at the bottom of the page.
before the fix (no search box at the top left corner of the page):
after the fix (search box is present!):
https://www.loom.com/share/f6b21d067a0f48ee9ed3a8d6a3577506
> [W-11541098] make search box stickier

- src/js/01-nav.js
- src/partials/banner.hbs
ref: [W-11558561](https://gus.lightning.force.com/a07EE000013OtsfYAC)
Add a new variable `exclude` for antora-navigator.yml, which can be used to exclude certain sections to be part of the nav group. This is most beneficial for the archive site at the moment, and possibly for production site in the future if we have multiple nav groups.
tl;dr (~7 minutes long) https://www.loom.com/share/446c56bddbbc4e18aa7e12aac6db13d1
As an example, let's say that in the archive site, here is my antora-navigator.yml:
```yml
groups:
- root: true
components: home
- title: Docs by Product
components: ['*', tcat-server]
output_file: site-navigation-data.js
```
and my playbook.yml branches:
```yml
content:
sources:
- url: https://github.com/mulesoft/docs-connector-devkit
branches: v3(.){2..4}
- url: …
```
> [W-11558561] more flexible nav group organization

- src/js/01-nav.js
ref: [W-11549560](https://gus.lightning.force.com/a07EE000013HtpRYAS)
In https://github.com/mulesoft/docs-site-ui/pull/172, a logic is added where if the icon for an item doesn't exist, then automatically apply the muley icon. However, in https://github.com/mulesoft/docs-site-ui/pull/173, if `spreadSingleItem` is not true or not set, then each of the sub-items also receive a Muley icon, which looks rather funny:
This PR adds a little bit more logic so that Muley icons will only be set if `spreadSingleItem` is set to true. Otherwise, do not assign an icon.
> [W-11549560] fix bug

- src/partials/footer-content.hbs
ref: [W-11568618](https://gus.lightning.force.com/a07EE000013cuc4YAA)
- remove languages from the footer dropdown that don't have docs available, namely Portuguese, German, and French
- update href links of English and Japanese sites to docs site instead of mulesoft.com
> [W-11568618] remove languages

- src/js/01-nav.js
[W-11613507](https://gus.lightning.force.com/a07EE000014KmzLYAS)
add a line which allows using the attribute `homeTitle` to override the name of the "home" icon. Primarily used for the archive site
https://www.loom.com/share/ba7847e3cde9484194e250ac15c327ed
> [W-11613507] add homeTitle

- src/css/adoc/doc.css
ref: W-10813707
exclude dataweave playground links from having the blue background when hovered. It wasn't supposed to apply to these buttons
> [W-10813707] bug fix - exclude dw playground links from blue background when hovered

- src/css/adoc/admonition-block.css
- src/css/adoc/doc-footer.css
- src/css/adoc/doc.css
- src/css/components/button.css
- src/css/components/card.css
- src/css/components/github.css
- src/css/components/popover.css
- src/css/components/select.css
- src/css/globals/global.css
- src/css/globals/reset.css
- src/css/globals/typography.css
- src/css/globals/vars.css
- src/css/pages/connector-article.css
- src/css/pages/connector-home.css
- src/css/pages/connector.css
- src/css/specific/gdpr.css
- src/css/specific/nav.css
- src/css/specific/notice-banner.css
- src/css/specific/toc.css
- src/css/vendor/coveo.css
- src/js/01-nav.js
ref: W-10592499, W-10813743
- make all actionable TOC items reachable by the keyboard TAB keys
- all expandable TOC items can be expanded or collapsed via mouse clicks and keyboard enter and space keys
- ~~when the nav group items are focused, expand them automatically so keyboard users can access the content within~~ (focus is easy to cause unwanted effects and makes the code messier)
note: although in the GUS ticket above, it stated that CSS is possibly in play to block the `<a>` elements to be focusable, but I can't find that CSS attribute. So tabindex is used instead
- increase contrast for some of the lighter-shaded elements so they pass the contrast ratio
https://www.loom.com/share/18a1f563249245649dd87160823053a9
> [W-10592499] make TOC items tabbable

- src/js/01-nav.js
ref: W-11799442
fix the issue where the archive site's Home nav item has the name "Home" when it should have been "Archive Home" instead.
Note that this is impossible to test locally because the key function, `isArchiveSite()`, looks for the base URL to modify the name, and you can't set that in a local setting..
> [W-11799442] fix archive site's home icon name

- src/css/specific/nav.css
- src/partials/github.hbs
- src/partials/header-content.hbs
ref: W-11836509
- exclude GitHub button rom the archive site only
- update header content
- force versions to have the dark gray color (I saw dark blue once once while reading the docs site on mobile)
1. run `gulp bundle` on this branch to create a local ui-bundle.zip
2. open docs-site-playbook, switch to the archive branch
3. [perform a local build](https://confluence.internal.salesforce.com/display/MTDT/Local+Build+Quick-Ref) using the local UI bundle. The archive site should not have the GitHub button on any of the pages
4. still on docs-site-playbook, switch to the default branch (m*ster)
5. repeat step 3 to perform a local build (with a smaller custom playbook to save time). The site should have the GitHub button on most of the pages
> [W-11836509] remove GitHub button from archive site

- src/css/specific/nav.css
- src/js/01-nav.js
- src/partials/header-content.hbs
ref: [W-11848524](https://gus.lightning.force.com/a07EE000017ppAhYAI)
- fix a bug where when focusing on a nav item in the left nav tree under "Docs by Product", the border does not show up. I believe this is because the CSS adds a border for the element when it is in the **focus-visible** state but not in the **focus** state, which causes different web browsers (including browsers with different versions and configurations) to interpret it differently.
- fix a minor bug when focusing on the nav version selector button, pressing the enter key twice (once to expand the menu, once to collapse it back) will not reset the versions' tabindex to -1, causing subsequent TABs to focus on the hidden versions. This is remediated by adding an additional check to reset the tabindex, in case the first …
> [W-11848524] fix focus border issue

- src/css/adoc/doc.css
ref: [W-10723677](https://gus.lightning.force.com/a07EE00000podylYAA)
Make the callout icons look like the annotation circles in the images:
> [W-10723677] update callout icons to match those in images

- gulp.d/tasks/build.js
- package-lock.json
- package.json
- src/css/adoc/doc.css
- src/css/components/popover.css
- src/css/components/tooltip.css
- src/css/globals/global.css
- src/css/specific/nav.css
- src/css/specific/notice-banner.css
- src/js/01-nav.js
- src/js/07-connectors.js
- src/js/10-notice-banner.js
- src/partials/notice-banner.hbs
ref: W-10592536
- add a blue dot indicator for the current version in the left nav version selector. The indicator has a tooltip that tells users what it means
- upgrade a library called tippy.js to the latest version
- add close button ("x") to deprecated notice banners to allow users to close it temporarily. It will display again when page is refreshed, no cookie is involved
current version indcator:
https://www.loom.com/share/5a84587a82384ae79d23a282f70fb259
notice banner close button:
https://www.loom.com/share/34e6a6a7a1934f5f86aaad183a6279f1
> [W-10592536] add current version indicator + notice banner close button

- src/css/components/tooltip.css
ref: [W-12029864](https://gus.lightning.force.com/a07EE00001BucOkYAJ)
the CSS change will allow the tooltip to show when hovering in the surrounding areas of the tooltip. This makes it easier to use the tooltip (in the screenshot below, the red circle indicates the rough hovering area)
> [W-12029864] make hovering area bigger

- src/css/components/tooltip.css
- src/css/specific/nav.css
ref: [W-11996638](https://gus.lightning.force.com/lightning/r/a07EE00001BKHzKYAX/view)
- fix a bug where on some web browsers (for example safari), when focusing on version selector buttons, the border does not show
> W-11996638 force version border gc

- src/css/specific/header.css
- src/partials/footer-content.hbs
ref: [W-10813743](https://gus.lightning.force.com/lightning/r/a07EE00000sL8LwYAK/view)
- update footer link colors to be more accessible
- remove a button called "Cookie Settings". It currently doesn't do anything so I took it out, but it should be back when we upgrade to the new footer.
> [W-10813743] update footer colors

- src/css/components/skiplink.css
- src/js/15-skiplink-listeners.js
ref: [W-12207708](https://gus.lightning.force.com/a07EE00001HIUuQYAX)
- make skip link focus state borders thicker:
- handle errors better for skip links:
- if a target section (left nav, main, or right nav) isn't present, the corresponding skip link is removed
- if there are no skip links, the entire skiplink div section is removed
> [W-12207708] thicker skip link focus borders

- src/helpers/release-notes.js
ref: [W-12221399](https://gus.lightning.force.com/a07EE00001HUHIwYAP)
handle error where the release notes helper function breaks the build if the release notes includes a partial from a repo that is not part of a playbook. For example, docs-release-notes has a partial from docs-rpa, but a beta site playbook includes docs-release-notes but not docs-rpa.
In the above scenario, the docs-rpa partial would simply be skipped, resulting in the following screenshot where there is supposed to be 5 releases listed in the "latest release" section, but it shows 4 instead since 1 of them has been skipped.
> [W-12221399] better error handling

- src/css/components/skiplink.css
ref: [W-12207708](https://gus.lightning.force.com/a07EE00001HIUuQYAX)
mark the skip link outline CSS as `!important` to override the default, so the border can show properly.
> [W-12207708] add !important tag to skip link

- src/partials/notice-banner/message-for-extended-support-banner.hbs
- src/partials/notice-banner/notice-banner.hbs
ref: W-12505704
Add extended support version banner.
This is done by having the following in a doc repo's antora.yml:
```yml
asciidoc:
attributes:
extendedSupport: true
```
> [W-12505704] add extended support banner

- preview-site-src/index.adoc
- src/helpers/release-notes.js
- src/js/02-table-of-content.js
ref: W-12466223
- add composer to be included in the "latest release notes" section
- fix page position by scrolling down for URLs that have an anchor. For example, open https://docs.mulesoft.com/release-notes/connector/amazon-s3-connector-release-notes-mule-4#6-1-0 would show the top of the section blocked by the marketing header
- add button role to the dropdown arrow introduced in #295 
- update preview site's index page
> [W-12466223] onboard composer to "latest release notes" section + fix initial scroll position

- src/partials/breadcrumbs.hbs
ref: W-12500977
Fix a bug where for each component's index pages, there still exists a duplicate entry in the breadcrumbs:
The solution is to add an additional condition check to exclude index pages. Below is the result:
> [W-12500977] remove duplicate breadcrumbs from index pages

- gulp.d/tasks/release.js
- src/partials/head/head-meta.hbs
ref: W-10592816
Update metadata:
- rename them to `mulesoft*` so they are separate than the `sf*` ones (the old metadata are kept for backwards compatibility)
- remove hyphens to be compatible with Coveo searches
Temporarily remove the capability to auto-create PR since the git commits created this way are unverified. See [W-10876368](https://gus.lightning.force.com/a07EE00000tMS2ZYAW) for further detail.
> [W-10592816] update metadata

- src/partials/head/head-meta.hbs
ref: W-12550440
This PR is an extension for the work #298, #304, #307, and #310. It's actually reverting many of the changes there, since I have learned how Coveo maps the metadata (need to document this later).
Here are the new set of metadata:
| Metadata Name         | Description     | Condition to appear |
|--------------|-----------|------------|
| product | name of the component     | always appear |
| is-latest-version      | if the page belongs to the latest version of a component  | only if the component has multiple versions. So it does not show up for `master` or `default` |
| latest-version | (if available) the latest version of the component | only if the component has multiple versions. So it does not show up for `master` or `default` |
| version | the version of the …
> [W-12550440] revert metadata

- src/css/globals/vars.css
ref: [W-12594329](https://gus.lightning.force.com/a07EE00001LnLr7YAF)
make modal z-index higher so that marketing header doesn't block it anymore.
> [W-12594329] adjust modal z-index

- src/css/specific/nav.css
- src/css/specific/top-banner.css
- src/js/15-coveo.js
ref: [W-12637932](https://gus.lightning.force.com/a07EE00001MQRQvYAP)
- regression bug fix - enforce max height for both left and right navs. Previously the bottom of the navs were not reachable
- accessibility fix - move submit button to the left of the input, so that screen magnification users can see the submit button. Previously those users may have missed the submit button if they have magnified the screen too much. Screenshot below shows the end result
> [W-12637932] move submit button + navs height bug fix

- src/js/01-nav.js
- src/partials/notice-banner/banner-latest-version-snippet.hbs
- src/partials/notice-banner/eol-reached/banner-for-eol-reached.hbs
ref: W-12648204
add extra logic to the nav javascript so that when a user scrolls to the bottom of the page, the user is able to scroll the left nav all the way to the top
add an extra attribute `latestVersionSwitch` to suppress the "switch to the latest version" clause. This satisfies a use case where for certain old versions where migration is too complex to the latest version, we want to omit the clause.
Usage:
```yml
name: runtime-fabric
title: Runtime Fabric
version: '1.8'
nav:
- modules/ROOT/nav.adoc
asciidoc:
attributes:
supportStatus: eolSupportVersion
latestVersionSwitch: false
```
Also remove `and is no longer supported.` at the end of the `eolReached` status banner.
> [W-12648204] left nav height adjust + status banners

- gulp.d/tasks/release.js
ref: [W-12660819](https://gus.lightning.force.com/a07EE00001Mm0HAYAZ)
add to `gulp release` command the ability to update the `ui-bundle.zip` file in the release named [latest](https://github.com/mulesoft/docs-site-ui/releases/tag/latest). This allows beta and internal (and review) sites to permanently pin to the UI bundle `https://github.com/mulesoft/docs-site-ui/releases/download/latest/ui-bundle.zip`.
also performed some code refactoring.
If you would like to test this locally, here are the steps:
1. export your Github token via `export GITHUB_TOKEN=<your token>`
2. in docs-site-ui's root project directory, run `gulp release`. Ensure that no errors are present
3. open https://github.com/mulesoft/docs-site-ui/releases and see that there is a new release named prod-* that released "now" …
> [W-12660819] add latest version release

- src/css/specific/banner.css
- src/layouts/default.hbs
- src/layouts/search-page.hbs
ref: W-12773381
fix position in the search page were scrolling down would cause the top banner to hide the search toolbar:
the root cause was that the search page layout is different than the other pages, so the CSS did not apply due to selector mismatching. I fixed it by adding an extra div in the search page layout around the <main> section, and then loosen up the CSS selectors.
Also formatted **default.hbs** with no changes. Just making it easier to read in the future.
> [W-12773381] fix top banner and toolbar positions in search page

- src/js/02-table-of-content.js
- src/js/14-skiplink-listeners.js
- src/partials/connectors/connectors-sidebar.hbs
- src/partials/toc.hbs
ref: [W-10813720](https://gus.lightning.force.com/a07EE00000sL8LZYA0)
- rename `js-toc` class to `aside-toc`. Seems more fitting
- revise skiplink listener logic so that if `aside-toc` doesn't exist, skip link is removed
> [W-10813720] remove skiplink for page navigation (right nav) if page nav doesn't exist

- src/js/vendor/coveo.bundle.js
- src/partials/head/head-scripts.hbs
- src/partials/search/search-result-template.hbs
ref: W-13003849
- upgrade atomic (search UI) which includes a number of accessibility fixes
- fix a bug where the facet heading is using the <h1> tag instead of <div>
- add inline CSS for the search result links to match the states of the links in other docs pages
> [W-13003849] upgrade atomic library

- src/css/specific/nav.css
- src/css/specific/toc.css
- src/css/vendor/tabs.css
ref: [W-13014519](https://gus.lightning.force.com/a07EE00001OwgyHYAR)
based on this StackOverflow answer: https://stackoverflow.com/a/23818110, when a user is hovering the mouse on certain texts to make them bolder, decrease letter spacing so the element width stays more consistent.
Before:
After:
Also fixed a minor regression bug where certain elements lost the outline when keyboard-focused.
> [W-13014519] decrease bold text letter spacing

- src/css/adoc/doc.css
ref: W-13008341
add top and bottom margins to images in the docs site main section to give it more space.
> [W-13008341] add top and bottom margins

- src/helpers/release-notes.js
ref: W-13020917
Bug fix. Remove duplicate release notes version if it exists in the original title:
> [W-13020917] remove duplicate release notes version

- src/css/components/button.css
- src/css/globals/global.css
- src/css/globals/reset.css
- src/css/globals/vars.css
- src/css/pages/home.css
- src/css/specific/banner.css
- src/css/vendor/coveo.css
- src/js/10-banner.js
- src/js/vendor/coveo.bundle.js
- src/layouts/home.hbs
- src/partials/head/head-meta.hbs
- src/partials/notice-banner/banner-for-no-longer-updated.hbs
- src/partials/notice-banner/banner-for-old-version.hbs
- src/partials/notice-banner/eol-reached/banner-for-eol-reached-feature.hbs
- src/partials/notice-banner/eol-reached/banner-for-eol-reached-version.hbs
- src/partials/notice-banner/eol-reached/banner-for-eol-reached.hbs
- src/partials/notice-banner/eol-scheduled/banner-for-eol-scheduled-feature.hbs
- src/partials/notice-banner/eol-scheduled/banner-for-eol-scheduled-version.hbs
- src/partials/notice-banner/eol-scheduled/banner-for-eol-scheduled.hbs
- src/partials/notice-banner/eol-support/banner-for-eol-support-feature.hbs
- src/partials/notice-banner/eol-support/banner-for-eol-support-version.hbs
- src/partials/notice-banner/eol-support/banner-for-eol-support.hbs
- src/partials/notice-banner/extended-support/banner-for-extended-support-feature.hbs
- src/partials/notice-banner/extended-support/banner-for-extended-support-version.hbs
- src/partials/notice-banner/extended-support/banner-for-extended-support.hbs
- src/partials/notice-banner/notice-banner.hbs
- src/partials/search/search-result-template.hbs
- src/partials/toolbar/search-toolbar.hbs
- src/partials/top-banner.hbs
refs:
- W-12632930
- [W-13029314](https://gus.lightning.force.com/lightning/r/a07EE00001PN060YAD/view)
_all screenshots in the following sections show before on the left, and after on the right_
adjust wording, behavior, look.
update banner close buttons from using a special character (x) to using a more proper SVG image
added CSS to make landing page links bold
> [W-12632930, W-13029314] adjust close buttons + landing page font weight

- src/css/adoc/doc.css
- src/css/specific/nav.css
- src/js/17-image-margin.js
- src/js/17-image-margins.js
ref: W-13065345
Fix 2 bugs.
regression bug from #369, where margins were also applying to icons. Reverted the CSS change and instead, applying a javascript to add the margins if the images are big enough
regression bug from #376, where extra right padding was applied to nav items that do not need that padding. Corrected the CSS so that certain nav items are excluded from having padding changes, and also adjusted the padding change values to further minimize the chance of number of lines changing
> [W-13065345] 2 bug fixes: image top/bottom margin + nav item width

- src/css/specific/nav.css
- src/js/01-nav.js
ref: W-13199049 + [W-13198917](https://gus.lightning.force.com/a07EE00001RK5gGYAT)
Improve the left nav for the archive site https://archive.docs.mulesoft.com/:
- set minimal width for nav items to preserve the nav item into a single line
- add "Archived Versions" as the label of the version selector to make it more clear what the versions are
Before:
After:
> [W-13199049 + W-13198917] enhance archive site's left nav

- src/js/19-survey.js
- src/js/20-mobile-survey.js
ref: W-13667862
previously, the customer feedback survey only shows to 5% of the people as the pilot phase. Now that the pilot phase is done, this PR removes the % check logic, so everyone in eligible countries will see the survey.
> [W-13667862] release customer feedback survey to all

- src/js/21-coveo-facets.js
- src/partials/head/head-meta.hbs
ref: [W-13887420](https://gus.lightning.force.com/a07EE00001XcR1aYAF)
- remove page metadata that is causing the badge to show
- revert sort order for versions since the current sort order sometimes incorrectly moves older versions to the top
> [W-13887420] bug fix - all search results have "latest version" badge

- src/css/adoc/doc.css
ref: W-13855859
add a bit more space between the code snippet and the elements below it. The following screenshot shows how it will look:
> [W-13855859] add extra bottom margin

- src/css/adoc/doc.css
ref: [W-13855859](https://gus.lightning.force.com/a07EE00001XKPn5YAH)
#504 added the capability for long code snippets to be collapsible. However, the overlay that added the "fading white edge" at the bottom was covering the code snippet, which means that people can't highlight the code or click the copy button until the code snippet is expanded.
This PR makes the code block overlay much shorter, which means that it is not blocking the code snippet's elements except for the very bottom, while retaining the same apperance.
> [W-13855859] adjust code block overlay height

- preview-site-src/elements/table.adoc
- src/css/adoc/table.css
When a table cell has multiple paragraphs, there should be spacing between the paragraphs.
**Testing**:
Added test table to preview site which displays properly:
> Add spacing between paragraphs in a table cell

- src/css/adoc/doc.css
- src/css/components/popover.css
- src/js/01-nav.js
- src/js/18-scroll-positions.js
- src/js/23-copy-link-button.js
- src/js/vendor/icondefs.js
Experimented with multiple options including the proposals in the work item. In the end, I matched the Salesforce Docs functionality:
<https://sfdocs-help.herokuapp.com/docs/success/sfdocs/guide/prerequisites.html#git-and-github>
Here's what that looks like:
On hover:
On click:
Testing:
* Confirmed copying to clipboard succeeds.
* Confirmed display of tooltips on mobile, medium, and large screens.
* Confirmed keyboard navigation works as expected. (You can tab to focus and pressing enter copies to clipboard.)
> [W-11911033] Change section anchors to copy link button

- src/css/adoc/doc.css
Code snippets in callout lists should display the border and light background that all other inline code snippets display.
Note that an alternate fix would have been to change the CSS selector to `& code` directly (to match all code snippets in the doc). I confirmed that works as well, but I was wary of unintended consequences, so I kept things scoped it down. If the broader scope is preferred, LMK and I can do that instead.
Note that I went ahead and confirmed during testing that code snippets already display correctly (with the background) in all other lists and tables.
**Before fix**
**After fix**
> [W-14080808] Fix: Code snippets display incorrectly in callout lists

- src/partials/landing-page/landing-page.hbs
- src/partials/landing-page/trending-topics.hbs
ref: [W-12474663](https://gus.lightning.force.com/a07EE00001KTGkvYAH)
- requested by Hanna via [this Slack message](https://salesforce-internal.slack.com/archives/G02H6FZJD/p1698188329180309?thread_ts=1693416547.865229&cid=G02H6FZJD) to rename the "Popular Topics" section to "Trending Topics"
- fix the number of recommendations to 7
> [W-12474663] rename "popular topics" to "trending topics" to match SF 

- src/partials/footer/footer-content-jp.hbs
- src/partials/head/head-scripts.hbs
- src/partials/toolbar/breadcrumbs.hbs
ref: W-14086638
- add version to breadcrumbs so that it's easier for users to see what the version they are currently in
- separate the Coveo scripts into 2 blocks: 1 for Trending Topics, and another for Coveo User Analytics+Search. This fixes the issue where internal beta sites cannot displaying trending topics because they weren't built with the Coveo API search key (on purpose, to avoid hitting usage quota)
> [W-14086638] add version to breadcrumbs + separate Trending Topics with Coveo UA/Search 

- gulp.d/tasks/build.js
- src/js/04-feedback.js
- src/locales/feedback-questions.json
- src/locales/survey-ids.json
ref: W-14400837
This PR has 2 purposes: separating survey IDs for different MuleSoft sites and cleaning up.
Revert the logic of #583 where prod site has its own ID and other sites use the same. Now each site type gets its own!
- Use the same implementation from #576 to move the feedback questions into its own JSON file
- Change some for loops to for-of
Should I have created another folder for the new json files instead of using **locale/**?
> [W-14400837] revise survey ID logic + clean up

- preview-site-src/ui-model.yml
- src/css/pages/home.css
- src/partials/landing-page/landing-page.hbs
- src/partials/toolbar/breadcrumbs.hbs
ref: [W-14416061](https://gus.lightning.force.com/a07EE00001diY5cYAE)
A continuation of #585.
If the page is the index page of a product, the version does not show in the breadcrumbs:
This PR added the logic to make the version show. Here's a screenshot of my local build for validation:
remove the "latest release" section from JP site since it doesn't have a release notes component. The "Trending Topics" section has the same look, just centered. Confirmed with Glenn that it is acceptable.
> [W-14416061] add version to breadcrumbs root label + remove "latest release" section from JP site

- src/partials/landing-page/landing-page.hbs
- src/partials/landing-page/latest-releases.hbs
ref: [W-14416061](https://gus.lightning.force.com/a07EE00001diY5cYAE)
In #587, the latest releases section was accidentally removed from the docs site. This PR brings it back
> [W-14416061] add back latest releases to docs site

- src/js/vendor/coveo.bundle.js
- src/partials/head/head-meta.hbs
- src/partials/head/head-scripts.hbs
- src/partials/head/head-scripts/coveo-search-scripts.hbs
- src/partials/head/head-scripts/coveo-ua-script.hbs
- src/partials/head/head-scripts/gtm-scripts.hbs
- src/partials/head/head-scripts/review-site-script.hbs
- src/partials/head/head-scripts/segment-script.hbs
- src/partials/head/head-scripts/vwo-script.hbs
- src/partials/nav.hbs
- src/partials/search/search-interface.hbs
- src/partials/search/search-result-template.hbs
- src/partials/toolbar/toolbar.hbs
ref: W-10592972
add JP site search. Some texts need to be localized later.
Also contains the following enhancements:
- break up head-scripts.hbs into multiple scripts, making it easier to see and manage
- change pages within the component "Home" to have "Getting Started" as the value of the metadata "product"
- upgrade atomic version
> [W-10592972] add jp site search

- src/css/adoc/doc-footer.css
- src/locales/feedback-questions.json
- src/partials/feedback-form/feedback-form.hbs
- src/partials/feedback-form/written-feedback-section.hbs
This PR makes (mostly subtle) changes to our feedback form styling based on comments from design, including:
* Change font size for all text to 16px.
* Remove bold from normal text--only titles should be in bold.
* Make minor changes to spacing to make text easier to scan.
* Update text to align with proposal from design.
As a nice to have, I streamlined some of the button css. In the wake of the One Salesforce reskin, we can now inherit these css values directly from the main `button.css` styles.
Here's a comparison:
**Old**
**New**
> [W-14470174] Incorporate feedback from design for feedback form

- src/js/vendor/coveo.bundle.js
- src/locales/messages.json
- src/partials/search/search-interface.hbs
- src/partials/toolbar/search-toolbar.hbs
- src/partials/toolbar/toolbar.hbs
Localize missing strings on search page. A couple of notes:
* The Coveo code does not interoperate well with our localization functionality. This is because their code uses web components and shadow dom, which by their nature, are isolated from the rest of the document. (You can't use `document.querySelector` without passing information about the containing component.) This means that in some places we're still using the old handlebars conditionals instead of our l10n code.
* I removed the "Docs" text from the search button as seen below. This button is shared on the results page and when you're typing, which means that if you put in the Japanese text, it's really squeezed for room. (Docs also doesn't translate well on its own--and Search Docs which we're using elsewhere is too long.)
> [W-14482220] Localize missing search page strings

- src/css/adoc/doc-footer.css
- src/js/04-feedback.js
This PR changes the feedback button styles so that the yes and no selected states match. (Previously, the yes state removed the icon when selected and increased in size.) It also adds a hover style for the thumbs icon.
Confirmed this displays as expected for all hover, selected and disabled states.
Selected state:
Hover state:
> [ W-14560307] Update feedback button styles after comments from design

- src/css/components/tooltip.css
- src/js/11-tooltip.js
ref: [W-14270710](https://gus.lightning.force.com/a07EE00001cCXDaYAO)
Per LevelAccess (our accessibility audit vendor) on the tooltip next to Archived Documentation link:
> Now the [tooltip] element is announced as a button, but is expected to perform an action when pressed. So the tooltip shouldn't appear automatically when focused, instead wait until the button is activated. Right now screen readers are not reading the tooltip in a regular navigation, only when focused with tab key, and that's not the expected behavior.
This PR changes the triggering behavior based on the recommendation. Now the tooltip becomes an actual button and tooltip will show only when 1) mouse hover or 2) click/press enter or space key. Focusing on it via the tab key will not show the tooltip.
Can validate the …
> [W-14270710] change tooltip triggering behavior

- src/css/adoc/doc-footer.css
- src/js/04-feedback.js
- src/partials/feedback-form/written-feedback-section.hbs
ref: W-14491991
- lower maximum character count 1000 -> 800
- add a simple visible character counter, modeled after the form in https://help.tableau.com/current/prep/en-us/about-tableau-help.htm:
Validated in local preview site (try http://localhost:8080/elements/admonition.html for reproduction). Tested the following:
- Once 800 characters have been added, no additional characters can be added
- Pasting content only pastes the first 800 characters
> [W-14491991] add feedback form char counter

- src/partials/head/head-scripts.hbs
ref: W-14901641
This PR reverts #649. #649 fixed the Google Analytics bug, but while inspecting the code some more, it was discovered that the google tag manager scripts (the ones needed for Google Analytics) was moved to a separate handlebar template file, and that file was accidentally omitted from the head-scripts.hbs. I have re-validated that the script and all other script files are now included.
> [W-14901641] reorganize head scripts

- preview-site-src/release-notes/by-date-index.adoc
- src/css/adoc/doc.css
- src/js/05-analytics.js
- src/partials/article/article.hbs
- src/partials/subheading/do-rss.hbs
- src/partials/subheading/subheading.hbs
This PR adds an RSS link on pages that include the `:page-subheading: rss` attribute. 
You can see the companion PR that adds that attribute to the release notes by-date page here:
https://github.com/mulesoft/docs-release-notes/pull/7863
Note that I've also added a tracking link modeled after our GitHub link, however I can't currently confirm the data is appearing until my access request goes through. Added a note to our existing tracking data spike to follow up on this.
> [W-14457826] Add RSS link for release notes

- src/partials/head/head-meta.hbs
After digging into how we can verify site ownership in Google Search Console, I realized that one of the methods was to add a meta tag to our pages (and moreover we were doing this previously as I found the old meta tags). Before, the meta tag was only being filled in on the prod site as it was the only site that had the key defined in the antora playbook. Since we now want to be able to verify all our sites, I'm adding the meta tag as default on all our pages. Note that Google does not generate different codes per site--rather the code is the same per account, so the one line in this PR _should_ be enough.
I'm also removing the old verification code from our playbook in the following PR:
https://github.com/mulesoft/docs-site-playbook/pull/2225
> [W-14955010] Replace meta tag for google site ownership verification

- preview-site-src-jp/jp/general/index.adoc
- preview-site-src-jp/jp/index.adoc
- preview-site-src/index.adoc
- src/js/21-coveo-facets.js
- src/partials/landing-page/landing-page.hbs
- src/partials/search/search-interface.hbs
ref: [W-15060125](https://gus.lightning.force.com/a07EE00001kITqGYAW)
fix bug. the [atomic-facet-manager](https://docs.coveo.com/en/atomic/latest/reference/components/atomic-facet-manager/) is supposed to automatically manager the order of the facets, but somehow it added the extra duplicate facet. After I removed it, this bug was fixed.
> [W-15060125] bugfix - remove duplicate "Filter by Products" facet in mobile view

- src/partials/head/head-scripts.hbs
- src/partials/head/head-scripts/coveo-ua-script.hbs
ref: W-15022269
- simplify the logic of having the Coveo UA script by checking for the existence of a Coveo API key environment variable rather than the site profile. The site profile is already being checked in the actual UA script so it's redundant
- harden the UA script so that Coveo UA is initialized only if a Coveo API key is found
> [W-15022269] harden Coveo UA script

- src/js/01-nav.js
- src/locales/messages.json
This PR moves the text for single-version badges, in other words version badges in the left nav without a drop-down, into our list of localized messages.
Here's what that looks like:
Note that the text has been made more generic to avoid issues with translating interpolated text. I've added this string to our upcoming handoff.
> [W-15145820] Localize single-version badge text

- src/js/00-globals.js
- src/js/24-jp-processing.js
For JP content only, wrap link text in Japanese brackets to match the localization style guide. Here's the guidelines we've received:
* Any section heading of a cross-reference needs to be bracketed with 「 and 」. (I'm taking this to mean links to page anchors, as those would be headings for a section.)
* Any document heading of a cross-reference needs to be bracketed with 『 and 』. (I'm taking this to mean direct links to pages.)
* Any cross-reference that occupies a whole block element (e.g. a list item or a table cell) should not be bracketed.
Additionally, I discovered during testing that there are several cases where bracket quotes were already added to link text manually during translation. As a result, I'm skipping wrapping if the text already contains brackets.
Tested in local …
> [W-15052351] Wrap JP Xrefs in Brackets

- preview-site-src/elements/element-examples.adoc
- src/css/specific/banner.css
When external links are added to notice banners, the link icon is too big.
Before:
After:
Tested on preview site only as this issue does not exist on beta (yet). This is something a writer will be adding soon.
> [W-15363939] Fix external link icon sizing in notice banners

- src/js/21-coveo-facets.js
- src/locales/messages.json
- src/partials/landing-page/trending-topics.hbs
Adding JP strings from HB.
Confirmed JP strings display in local preview:
> [W-15452675] Process FY25Q1 UI String Loc HB

- src/js/13-breadcrumbs.js
- src/partials/toolbar/breadcrumbs.hbs
This issue seems to be limited to children of the Gateway node in our docs, as the nesting is different. Here's what the issue looks like:
Fixing this by simply setting display none on any duplicate versions in the breadcrumbs. Tested in the preview site.
> [W-14944827] Fix: Breadcrumbs showing version twice

- src/css/specific/toolbar.css
- src/js/13-breadcrumbs.js
This PR fixes two issues:
* On mobile, the docs site shows a breadcrumbs toolbar on some pages where the desktop site does not show breadcrumbs. As a result, the breadcrumbs event listeners aren't being registered on those pages, which leads to the toggle button not working. Fixed this by moving a function call so that it always registers event listeners for breadcrumbs.
* The toggle button is stretched into an oblong shape. Fixed this by editing the toolbar CSS to exclude the toggle button, as its higher specificity was overriding the button height defined elsewhere.
Tested in preview build and in full playbook build.
> [W-15059890] Fix: Mobile breadcrumbs drawer not always toggling

- src/layouts/home.hbs
ref: W-15795774
minor fix for #715. Need parentheses are `site-profile` to get the site profile.
> [W-15795774] added missing parentheses

- src/helpers/connectors.js
The [connectors landing page](https://archive.docs.mulesoft.com/connectors/) for the archive site does not show all the connectors available. This was a strange one to debug as side-by-side comparisons of the content did not yield any noticeable differences, and the code in this repo does not have any special template for the archive connectors table. 
It turns out that this issue is caused by the Antora Atlas extension. The connectors list is generated based on the latest version of components (this list is created by Antora at build-time), and this list also includes versions of components from the [prod site's manifest](https://docs.mulesoft.com/site-manifest.json). These imported versions are always set as the latest version, which is a problem because imported versions do not include …
> [W-15230132] Fix: Archive connectors landing page missing connectors

- src/helpers/release-notes.js
ref: [W-16007932](https://gus.lightning.force.com/a07EE00001uUqR0YAK)
fix the regex that captures the version in the release notes page title and headings:
before (see API Manager):
after:
1. in docs-site-ui, run `npm run format:bundle` to export the build zip file
2. in docs-site-playbook, create a small playbook that only includes docs-general and docs-release-notes. Use the local build zip file (the file path to it) as the UI bundle 
3. perform a local build and open the local build landing page. It should show **API Manager 2.4.30** as one of the links in the Latest Releases section
> [W-16007932] fix latest release notes title

- gulp.d/tasks/update.js
- src/partials/footer/footer-content-en.hbs
- src/partials/header/header-content-archive.hbs
- src/partials/header/header-content-en.hbs
- src/partials/header/header-content-jp.hbs
ref: [W-16115512](https://gus.lightning.force.com/a07EE00001vTKC8YAO)
remove the helmet from the marketing header.
before:
after:
> [W-16115512] remove marketing header helmet

- preview-site-src/elements/miscellaneous.adoc
- src/css/adoc/collapsible-blocks.css
Discovered one more edge case after rolling out the new collapsible block styles.
Issue:
Fix:
> [W-15177355] Fix: Padding issue when collapsible blocks embedded in admonitions

- src/css/adoc/collapsible-blocks.css
Per the writing team, one of the main use cases for collapsible blocks is embedding in lists, and the new styles stand out too much.
We're reducing the size of collapsible blocks to fit the content better even if it's slightly inconsistent with Salesforce sizing.
Before and after:
> [W-16618856] Reduce size of collapsible blocks

- preview-site-src-jp/ui-model.yml
- src/js/21-coveo-facets.js
- src/layouts/home.hbs
- src/partials/head/head-scripts.hbs
- src/partials/head/head-scripts/coveo-ua-script.hbs
- src/partials/nav.hbs
- src/partials/search/search-interface.hbs
- src/partials/search/search-result-template.hbs
ref: W-16646670
Moving Coveo search from the mulesoft org to the salesforce org (dev). Most of the work is renaming fields and changing the org. 
Coveo User Analytics (UA) is not in scope, so there are no changes in the UA scripts until after the moratorium ends.
In 1password, search for **coveo token**. Copy the dev secrets for EN and JP site and export them as these variables (I have these added to my .zshrc file for convenience):
```sh
export COVEO_API_KEY=xx13....
export COVEO_API_KEY_JP=xx8...
```
Then run `npm run preview` and perform a search (example: http://localhost:8080/general/search.html#f-mulesoftproduct=Connector%20DevKit). Note that the local preview site doesn't have all the products and versions so most of the version facets (the ones that appear when you select a …
> [W-16646670] coveo migration

- gulp.d/tasks/release.js
ref: W-16084826
After a PR merge, instead of creating 3 separate PRs in docs-site-playbook, this now creates only 1 PR in the main branch to update all 3 playbooks there. Validated by running the script locally to create https://github.com/mulesoft/docs-site-playbook/pull/2677
Also did a little bit of clean up.
> [W-16084826] create PR in playbook main branch only

- src/css/vendor/coveo.css
- src/js/25-trending-topics-fallback.js
- src/js/vendor/coveo.bundle.js
- src/partials/head/head-scripts/coveo-search-scripts.hbs
- src/partials/header/header-content-archive.hbs
- src/partials/header/header-content-en.hbs
- src/partials/header/header-content-jp.hbs
- src/partials/search/search-interface.hbs
ref: W-15061326
- upgrade atomic library to 3 following the [upgrade guide](https://docs.coveo.com/en/atomic/latest/atomic-upgrade-from-v2/)
- update the search box field from <input> to <textarea> and adjust CSS accordingly
- update marketing header
- enhance the trending topics fallback logic to handle fallback better (right now if you go to https://beta.docs.mulesoft.com/beta-ui-staging/general/, the trending topic section shows nothing. This change fixes that)
the final product looks almost the same as the current one:
> [W-15061326] atomic library upgrade 2 -> 3

- preview-site-src/elements/admonition.adoc
- src/partials/notice-banner/eol-reached/banner-for-eol-reached-feature.hbs
- src/partials/notice-banner/eol-reached/banner-for-eol-reached-version.hbs
- src/partials/notice-banner/eol-reached/banner-for-eol-reached.hbs
- src/partials/notice-banner/eol-scheduled/banner-for-eol-scheduled-feature.hbs
- src/partials/notice-banner/eol-scheduled/banner-for-eol-scheduled-version.hbs
- src/partials/notice-banner/eol-scheduled/banner-for-eol-scheduled.hbs
- src/partials/notice-banner/eol-support/banner-for-eol-support-feature.hbs
- src/partials/notice-banner/eol-support/banner-for-eol-support-version.hbs
- src/partials/notice-banner/eol-support/banner-for-eol-support.hbs
- src/partials/notice-banner/extended-support/banner-for-extended-support-feature.hbs
- src/partials/notice-banner/extended-support/banner-for-extended-support-version.hbs
- src/partials/notice-banner/extended-support/banner-for-extended-support.hbs
Replaced all references to the old support link on help.mulesoft.com with the new Salesforce support policy.
Also, updated the inline EOL notes in this PR:
https://github.com/mulesoft/docs-reuse/pull/46
**Testing**
Tagged the admonition page in a preview build.
Ran a local build of docs-site-playbook with these changes.
> [W-17275164] Update EOL support link

- preview-site-src-jp/elements/admonition.adoc
- preview-site-src-jp/ui-model.yml
- src/partials/notice-banner/eol-reached/banner-for-eol-reached-feature.hbs
- src/partials/notice-banner/eol-reached/banner-for-eol-reached-version.hbs
- src/partials/notice-banner/eol-reached/banner-for-eol-reached.hbs
- src/partials/notice-banner/eol-scheduled/banner-for-eol-scheduled-feature.hbs
- src/partials/notice-banner/eol-scheduled/banner-for-eol-scheduled-version.hbs
- src/partials/notice-banner/eol-scheduled/banner-for-eol-scheduled.hbs
- src/partials/notice-banner/extended-support/banner-for-extended-support-feature.hbs
- src/partials/notice-banner/extended-support/banner-for-extended-support-version.hbs
- src/partials/notice-banner/extended-support/banner-for-extended-support.hbs
This PRs copies the translations from the [EOL notes in docs-reuse](https://github.com/mulesoft/docs-reuse-jp/blob/latest/modules/ROOT/partials/eol-note.adoc?plain=1) and uses it for our EOL banners which are currently English-only.
A couple of caveats:
* The [EOL support banners](https://github.com/mulesoft/docs-site-ui/tree/main/src/partials/notice-banner/eol-support) do not have translations as they don't have corresponding EOL notes in docs-reuse. However, there's only [one page](https://github.com/search?q=org%3Amulesoft%20%3Apage-support-status%3A%20eolSupport&type=code) in our docs currently using that banner. I think this is a rare enough case that it's fine to leave these alone, so I'm punting on requesting translations.
* I'm not including the `{{> banner-latest-version-snippet …
> [W-17405569] Localize EOL banner text

- src/css/specific/nav.css
- src/js/01-nav.js
Fixes this accessibility issue: https://knowledge.evinced.com/system-validations/nested-interactive
This is caused by the interactive button containing an interactive tooltip dot. From what I can tell, the offending button here is purely decorative: we remove it from tab navigation with `tabindex=-1`, and drop down part of the version control is outside of it. 
Switching from a button to a div seems to fix the problem. Also, though it wasn't strictly necessary, I went ahead and renamed the class to reflect the change. I.e.:
`button.nav-version-button` --> `div.nav-version-wrapper`
**Testing**
Tested in local preview.
Confirmed version drop-down still works.
Confirmed keyboard navigation remains the same.
> [W-17627075] Fix: Nav version should not contain nested interactive elements

- package-lock.json
- src/css/globals/global.css
- src/helpers/release-notes.js
ref: W-17901709
fix month format in the "Latest Releases" section.
before:
after:
validated via local build (`npm run format:bundle` then build it using a test playbook)
> [W-17901709] bugfix: latest releases month format

- src/css/pages/learning-map.css
- src/js/09-external-links.js
- src/js/vendor/icondefs.js
Added an icon for the learning map in the TOC:
Changed the behavior of external links in learning maps. Writers want these to open in new windows like they usually do. I'm still hiding the link icon though to avoid wrapping issues like this:
Fixed an issue where the first column of the learning map table had different spacing between lines than the others. It turned out there was something in table.css overriding the expected behavior. I tightened up the spacing while I was looking at it.
**Testing**
Tested in local preview.
Tested in full build.
> [W-17866218] Add learning map icon, fix alignment and margins

- src/partials/connectors/connectors-sidebar.hbs
This PR fixes issues found by our automated accessibility scan. Specifically, these three issues:
* https://knowledge.evinced.com/system-validations/interactable-role
* https://knowledge.evinced.com/system-validations/keyboard-accessible
* https://knowledge.evinced.com/system-validations/accessible-name
**Testing**
Confirmed in local preview that the sidebar button:
* Still displays as before visually.
* Still shows the tooltip on hover.
* Now, shows the tooltip when you tab to it.
> [W-17627146] Fix: A11y issues in connector sidebar button

- src/partials/toolbar/breadcrumbs.hbs
ref: [W-17952016](https://gus.lightning.force.com/a07EE00002Aa1D2YAJ)
this PR updates the breadcrumbs logic for checking root pages so that breadcrumbs are showing. If you run `{{log .}}` after line 20 of breadcrumbs.hbs, you can see something like this:
```json
{
content: 'DataWeave',
url: '/dataweave/latest/index.html',
urlType: 'internal',
items: [
{
content: 'Overview',
url: '/dataweave/latest/index.html',
urlType: 'internal'
},
{
content: 'Release Notes',
url: '/dataweave/latest/dataweave-release-notes.html',
urlType: 'internal'
},
{
content: 'DataWeave Quickstart',
url: '/dataweave/latest/dataweave-quickstart.html',
urlType: 'internal'
},
{
content: 'Language Guide',
url: '/dataweave/latest/dataweave-language-guide.html',
urlType: 'internal',
items: [Array]
},
{
content: 'DataWeave …
```
> [W-17952016] bugfix - breadcrumbs not showing gateway parent pages

- src/css/globals/global.css
- src/partials/head/head-links.hbs
- src/partials/head/head-scripts/coveo-search-scripts.hbs
ref: W-18013982
- adjust the top padding of the search bar so that it is no longer blocked by the agentforce promo banner
- upgrade coveo atomic library
- update analytics mode to legacy. This was recommended by our customer success manager Renee to allow user analytics events to process correctly. See [Coveo doc](https://docs.coveo.com/en/atomic/latest/usage/atomic-usage-analytics/#:~:text=Only%20Coveo%20for%20Commerce%20supports%20EP%20at%20the%20moment.%20For%20every%20other%20kind%20of%20implementation%2C%20set%20analyticsMode%20to%20legacy%20for%20the%20time%20being.) for further detail.
> [W-18013982] fix search bar CSS and set analytics mode to legacy

- src/css/adoc/doc.css
The lower margin of some TOC items is too big. This is fallout from the restructuring of the nav HTML for previous accessibility work, and affects TOC item which only have one version listed.
Example of extraneous spacing:
**Testing**
Tested in local preview.
> [W-18762356] Fix: Extraneous spacing after TOC items with single version badge

- src/css/vendor/docsearch.css
- src/partials/footer/docsearch-scripts.hbs
This change  allows users to search multiple versions of help. To prevent lots of of duplicate search results, we only return results from latest by default. However, if a user includes one or more version strings in their query, then we will dynamically update our version filter to include the specified versions and latest. I've carved out an exception for release notes, as those are all in latest--if the user searches on some variation of 'release', then we search latest to ensure that the user gets what they're expecting.
I also did some server-side configuration in Algolia to:
* Index all versions.
* Allow version data to be returned in responses.
* Deduplicate results to the same page. (Previously, I was handling this client-side, but found a way to do it server-side with …
> [W-19478445] Allow users to search multiple versions
