mulesoft/docs-site-ui

preview-site-src/tests.adoc
src/css/adoc/doc.css

TODO: Need to add tests.adoc to the preview site build.

DOCSINFRA-144 adding/updating files. [DO NOT MERGE]

---

package-lock.json
package.json
preview-site-src/index.adoc
preview-site-src/ui-model.yml
src/css/adoc/doc.css
src/css/components/button.css

DOCSINFRA-166 add primary button styles (.button-primary)

---

gulp.d/tasks/build.js
src/js/07-connectors.js

* remove obsolete function in script for connectors
* include partials from subdirectories in bundle

Fix Gulp build

---

preview-site-src/index.adoc
src/css/components/button.css

DOCSINFRA-173 styles for code in button-primary

---

src/js/01-nav.js

* only attempt to relativize a root-relative URL
* fix scope of local variables in toggleNav function
* don't fail if navigation for product is missing
* use display version if defined for current version

Fix various problems in navigation code

---

preview-site-src/ui-model.yml
src/css/specific/navigation.css
src/js/01-nav.js

This PR implements the navigation for connectors. That entails moving the navigation for the individual connectors to the bottom of the Connectors navigation children. These items still behave like top-level navigation items, but only appear when the Connectors item has been activated.

DOCSINFRA-161 Connectors navigation

---

src/js/01-nav.js
src/layouts/default.hbs
src/partials/connectors/connectors-article.hbs
src/partials/connectors/connectors-table.hbs

- use icon from exchange
- use generic icon in nav
- apply connector-article layout to module pages

DOCSINFRA-193 fix connector icons and module pages

---

src/css/pages/connector-home.css

fix connectors overflow

---

gulp.d/tasks/build-preview-pages.js
preview-site-src/ui-model.yml

These changes important new functionality from the default UI.

DOCSINFRA-249 Preview build updates

---

gulp.d/tasks/release.js

The property that passes the file contents to the upload release asset API was renamed from file to data. Also remove the origin/ prefix if present on the branch.

DOCSINFRA-253 fix release task

---

src/partials/head-meta.hbs

Here is the corresponding change to the playbook: https://github.com/mulesoft/docs-site-playbook/pull/606

DOCSINFRA-256 adding site key for GSC.

---

Jenkinsfile

ref: [W-10592589](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000laXxVYAU/view)
replace team github credentials with shared github credentials

[W-10592589] Update cred ID

---

src/css/components/clipboard.css
src/js/vendor/coveo.js

ref: W-11350032
fix 2 errors:
1. When clicking on the code snippet copy button, the "Copied" UI feedback no longer shows. Changing the color in CSS made it appear again.
2. Modal window search box is no longer being auto-focused because a previous clean up effort removed the code. I added back the code

[W-11350032] regression errors

---

README.adoc
gulpfile.js
src/css/specific/header.css
src/partials/header-content.hbs

ref: [W-11430259](https://gus.lightning.force.com/a07EE000011T3boYAC), [W-11430226](https://gus.lightning.force.com/a07EE000011SzQ4YAK)
- fix bug where on mobile, the navigation button is hidden under the top-level menu
- fix bug where on mobile, global search is hidden under the Mulesoft logo
- change the port number from 5252 to 8080 so that we can use Sauce Labs to perform a manual test for the local build. Port 5252 is not supported by Sauce Labs ([source](https://docs.saucelabs.com/secure-connections/sauce-connect/faq/#supported-browsers-and-ports))
- format header content so it's easier to see the changes in future PRs (will update instructions in Confluence)

[W-11430259] breadcrumb + search bug fixes

---

src/js/08-code-snippet-toolbar.js

ref: [W-11267884](https://gus.lightning.force.com/a07EE00000ynUIKYA2)
update logic so that only the "include" code snippets have the try-me button. Validated via local build

[W-11267884] disable tryme button for some snippets

---

preview-site-src/element-examples.adoc
src/partials/github.hbs

ref: W-10592813
- remove github edit_url manipulation since that will be done on the playbook instead
- refactor github.hbs to remove duplicate content
- remove unused mathjax examples
https://www.loom.com/share/95c2b52724234b6988618bf0a82bd6b7

[W-10592813] GitHub url

---

package-lock.json
src/css/components/code-snippet-toolbar.css
src/css/site.css
src/js/08-code-snippet-toolbar.js

ref: W-11267884, https://github.com/mulesoft/docs-site-playbook/pull/975
- made CSS and JS updates to match the [UX design](https://www.figma.com/proto/PDRhfYkeg9Uw7s7zeiJTHR/docs_dataweave?page-id=0%3A1&node-id=3%3A4&viewport=4078%2C1148%2C0.86&scaling=min-zoom) for the dataweave "try me" button
- update code snippet logic to allow try me button in dataweave-related code snippets, including XML and JSON snippets
- minor clean up
https://www.loom.com/share/da35d7346dc44074b01eb5b706c19834

[W-11267884] dataweave button - UI update from ux feedback

---

src/css/components/modal.css
src/css/globals/reset.css
src/css/globals/vars.css
src/css/specific/nav.css
src/css/vendor/coveo.css
src/js/vendor/coveo.js
src/partials/search.hbs

ref: W-10813712
accessibility changes:
- darken search boxes and placeholder text to satisfy minimum contrast ratio
- add "Search Docs" label in the search modal to explain input
- adjust search modal filter max width so it looks better
https://www.loom.com/share/db5f0a89a5fa49d7ab4acebff61d405d

[W-10813712] search modal accessibility enhancements

---

src/css/globals/reset.css
src/css/specific/nav.css
src/js/01-nav.js

ref: W-10813721
Accessibility changes for the left nav tree toggle buttons (+ and -):
- add aria labels to explain the name and state
- add button type to explain the role
- add border to focus state to allow visual cue when using keyboard to navigate the website
https://www.loom.com/share/bb8a6748271547ba8dfd937d660a5573

[W-10813721] add aria labels gc

---

src/css/adoc/doc.css

ref: [W-11963080](https://gus.lightning.force.com/a07EE000019zDLgYAM)

[W-11963080] increase code snippet vertical padding length

---

src/partials/connectors/connectors-popular.hbs

ref: [W-11964711](https://gus.lightning.force.com/a07EE00001A0rHdYAJ)

[W-11964711] exclude "popular connectors" section from archive site

---

src/css/specific/toc.css
src/partials/github.hbs

[W-12030048] make right sidebar sticky at the bottom of the page

---

src/css/specific/nav.css

ref: W-11894591
related to #213

W-11894591 minor CSS fix for visual indicator

---

src/css/specific/toc.css

ref: [W-10813749](https://gus.lightning.force.com/a07EE00000sL8M2YAK)
enhance the right nav visual indicators:

[W-10813749] update right nav states

---

src/partials/head-scripts.hbs

ref: [W-12181797](https://gus.lightning.force.com/a07EE00001GTWr1YAH)
- replace old GTM script with a new one
- add onclick script to capture common area clicks

[W-12181797] replace gtm script

---

src/partials/head-scripts.hbs

ref: W-12181797
Related to #266. I added old GTM script back, but update GTM container ID.

[W-12181797] fix GTM script

---

src/js/14-vwo.js

ref: [W-12096977](https://gus.lightning.force.com/a07EE00001E1CLUYA3)
add a comma

[W-12096977] fix VWO script

---

src/js/14-vwo.js

ref: [W-12096977](https://gus.lightning.force.com/a07EE00001E1CLUYA3)
update VWO goal ID

[W-12096977] update VWO goal ID

---

src/css/pages/home.css
src/js/01-nav.js
src/partials/head-scripts.hbs

ref: W-12214056
- for new landing page button, add CSS for active/focus state (note the light blue border)
- refactor
- (testing) comment out the segment analytics code to test Google tag manager analytics

[W-12214056] active state button gc

---

src/partials/head-scripts.hbs

ref: W-12181797
staging this PR in case we need to revert segment script

[W-12181797] add segment script block back

---

gulp.d/tasks/get-marketing-content.js
src/css/globals/vars.css
src/css/specific/header.css
src/js/01-nav.js
src/partials/footer/footer-content-en.hbs
src/partials/header/header-content-archive.hbs
src/partials/header/header-content-en.hbs
src/partials/header/header-content.hbs
src/partials/nav.hbs
src/partials/search.hbs

ref: [W-11910766](https://gus.lightning.force.com/a07EE000018osbbYAA)
- fix z-index for search module
- fix header position CSS
- update header/footer content

[W-11910766] fix header position bug gc

---

src/js/08-code-snippet-toolbar.js
src/partials/header/header-content-archive.hbs
src/partials/header/header-content-en.hbs

ref: W-12481827
- fix dataweave playground link (the previous one gets stuck sometimes)
- update header content

[W-12481827] fix dataweave playground links

---

src/partials/breadcrumbs.hbs

ref: W-12500977
remove redundant breadcrumbs item

[W-12500977] remove extra breadcrumbs

---

src/partials/head/head-scripts.hbs
src/partials/header/header-scripts.hbs

ref: [W-12490063](https://gus.lightning.force.com/a07EE00001KctwUYAR)
add nonce to the GTM script (may or may not work. Testing)

[W-12490063] add nonce

---

src/partials/head/head-meta.hbs

ref: W-10592816
also add latest-version metadata, so we can possibly use it to identify the latest version in the search results.

[W-10592816] unify product metadata value for connectors

---

src/partials/head/head-meta.hbs

ref: W-12550440
adjust page metadata

[W-12550440] update metadata

---

src/css/components/tooltip.css
src/js/01-nav.js
src/partials/search/search-interface.hbs

ref: [W-10813722](https://gus.lightning.force.com/a07EE00000sL8LbYAK)
accessibility fixes for the span that triggers the tooltips:
- remove the `tool-tip` role. This role should be added to the tooltip container itself, not the span that triggers the tooltips
- remove unnecessary CSS from the span

[W-10813722] fix accessibility issues for the tooltip spans

---

src/js/15-coveo.js

ref: [W-10813746](https://gus.lightning.force.com/a07EE00000sL8LzYAK)
accessibility fix. Update the assistive text for the search box input to make it clear that this search field is for Docs search instead of mixing it up with the other search boxes

[W-10813746] update assistive text for the search box input

---

src/js/01-nav.js
src/partials/head/head-scripts.hbs
src/partials/landing-page/latest-releases.hbs
src/partials/toolbar/breadcrumbs.hbs
src/partials/toolbar/toolbar.hbs

ref: W-11470312
- upgrade Segment version (Segment is the platform that receives analytics data from the docs site and sends it to Amplitude to visualize). This may or may not resolve the issue where some analytics data is not being received in Amplitude
- clean up HTML based on the results in https://validator.w3.org/nu/?doc=https%3A%2F%2Fdocs.mulesoft.com%2Fgeneral%2F

[W-11470312] upgrade segment, clean up HTML

---

src/css/specific/nav.css
src/css/specific/top-banner.css
src/js/01-nav.js
src/js/03-mobile-navbar.js
src/partials/nav.hbs
src/partials/toolbar/breadcrumbs.hbs

refs:
- W-12500977
- W-12648204
index page link -> text (non-link)
implement event listener to adjust height based on scroll position and screen size
make search box sticky at the very bottom of the page

[W-12500977, W-12648204] adjust breadcrumbs + fix left nav height

---

gulp.d/tasks/release.js
src/js/04-feedback.js
src/partials/head/head-scripts.hbs
src/partials/header/header-content-jp.hbs

ref: W-12660119
Similar to #337, but allow the initial search to happen only in the search page, otherwise no search result would show initially on that page. 
Also fixed a logic error on the feedback card, where if no feedback card is present in the current page (like the search page for example), then it generates an error.
Finally, updated JP site header content.

[W-12660119] fix search error

---

src/css/components/breadcrumbs.css
src/css/globals/global.css
src/css/globals/vars.css
src/css/specific/nav.css
src/css/vendor/coveo.css
src/js/02-table-of-content.js
src/partials/search/search-interface.hbs
src/partials/toolbar/breadcrumbs.hbs
src/partials/toolbar/toolbar.hbs

ref: W-12673659
- adjust page overall height so that the mobile toolbars don't block the bottom edge of the content
- increase width for both the left nav and the version selector boxes
- fix breadcrumbs bug so that the current page breadcrumb is always be a link
- allow adjusting the scroll positions based on whether the banners are present or not

[W-12673659] fix mobile issues

---

package-lock.json
package.json
src/css/components/breadcrumbs.css
src/partials/head/head-meta.hbs
src/partials/header/header-content-archive.hbs
src/partials/header/header-content-en.hbs

refs:
- [W-12779164](https://gus.lightning.force.com/a07EE00001O9TXVYA3)
- [W-12777367](https://gus.lightning.force.com/a07EE00001O8USkYAN)
- upgrade node-fetch. The old version of node-fetch appears to no longer fetching marketing content
- using the new version of node-fetch to fetch the new marketing header code. Minor change - only phone number is updated
- remove breadcrumbs max width. it should not exist
- add description metadata to help with SEO

[W-12779164] update phone number + upgrade node-fetch + add description metadata

---

src/css/specific/banner.css
src/layouts/default.hbs
src/layouts/search-page.hbs

ref: W-12773381
The `container` class has a max-width that makes the search page main section too narrow. I removed this class from the search page div and adjusted CSS accordingly.

[W-12773381] adjust top banner width

---

Jenkinsfile
src/css/specific/banner.css
src/js/10-banner.js
src/layouts/search-page.hbs
src/partials/notice-banner/banner-for-no-longer-updated.hbs
src/partials/notice-banner/banner-for-old-version.hbs
src/partials/notice-banner/eol-reached/banner-for-eol-reached-feature.hbs
src/partials/notice-banner/eol-reached/banner-for-eol-reached-version.hbs
src/partials/notice-banner/eol-reached/banner-for-eol-reached.hbs
src/partials/notice-banner/eol-scheduled/banner-for-eol-scheduled-feature.hbs
src/partials/notice-banner/eol-scheduled/banner-for-eol-scheduled-version.hbs
src/partials/notice-banner/eol-scheduled/banner-for-eol-scheduled.hbs
src/partials/notice-banner/eol-support/banner-for-eol-support-feature.hbs
src/partials/notice-banner/eol-support/banner-for-eol-support-version.hbs
src/partials/notice-banner/eol-support/banner-for-eol-support.hbs
src/partials/notice-banner/extended-support/banner-for-extended-support-feature.hbs
src/partials/notice-banner/extended-support/banner-for-extended-support-version.hbs
src/partials/notice-banner/extended-support/banner-for-extended-support.hbs
src/partials/notice-banner/notice-banner.hbs

ref: W-12690315
please review #361 first before this, since this PR contains the changes in #361 (because if I do not contain those changes, there will be a merge conflict which would require an extra approval).
Implemented all the changes described in https://www.loom.com/share/ea51e3485276485ab01beec7ad47939c
Also updated Jenkinsfile to allow releasing new version if node dependencies are updated.

[W-12690315] fix banner related look & feel issues

---

src/css/vendor/tabs.css

ref: W-12992788
fix bugs described in the ticket

[W-12992788] Add asciidoc tabs

---

src/css/globals/vars.css

ref: W-13029314
updating the fonts to match with mulesoft.com's

[W-13029314] match font family with mulesoft.com

---

src/css/globals/vars.css

ref: W-13029314
an extension of #373. Correct the font names provided in the header-footer.css (the names are different than those in mulesoft.com).

[W-13029314] correct font

---

src/css/globals/vars.css
src/css/specific/nav.css
src/css/specific/toc.css
src/css/vendor/tabs.css
src/helpers/release-notes.js

ref: W-13020917
- enhance "latest release" logic
- increase slightly the letter spacing for the new font and add boldness

[W-13020917] better release notes logic fix + letter spacing adjustment

---

src/css/globals/vars.css
src/css/specific/nav.css
src/css/specific/toc.css
src/css/vendor/normalize.css
src/css/vendor/tabs.css
src/layouts/search-page.hbs

refs: 
- W-13014519
- [W-13029314](https://gus.lightning.force.com/a07EE00001PN060YAD)
- [W-10813726](https://gus.lightning.force.com/a07EE00000sL8LfYAK)
- increase letter spacing (-0.1em -> -0.005em) when hovered to increase readability
- add right padding when not hovered, to make the layout more predictable
- fix a minor bug where all version selector texts become bold
move checkmark to the right of the left nav version selector box

[W-13014519, W-13029314, W-10813726] adjust nav item padding and letter spacing + checkmark placement

---

src/css/adoc/abstract.css
src/css/adoc/admonition-block.css
src/css/adoc/description-list.css
src/css/adoc/doc-footer.css
src/css/adoc/doc.css
src/css/components/button.css
src/css/components/card.css
src/css/globals/typography.css
src/css/pages/connector-article.css
src/css/pages/connector-home.css
src/css/pages/connector.css
src/css/specific/banner.css
src/css/specific/nav.css
src/css/specific/toc.css
src/css/vendor/normalize.css
src/css/vendor/tabs.css

ref: W-13068964
Since the font has changed on the docs site, we need to adjust the behavior to adjust the font weight (aka boldness) by changing the `font-family` property instead of `font-weight`. 
Also fixed a minor bug with the EOL banner position where the EOL banner is too low.

[W-13068964] fix font weight

---

preview-site-src/elements/code-block.adoc
src/css/adoc/doc.css
src/js/01-nav.js
src/js/03-mobile-navbar.js
src/js/10-banner.js
src/js/13-breadcrumbs.js
src/js/17-image-margin.js
src/js/vendor/coveo.bundle.js

refs: 
- W-13120528
- [W-13121643](https://gus.lightning.force.com/a07EE00001QP4krYAD)
- fix breadcrumbs bug + refactor code so it's easier to maintain
- minor refactoring of the code
Fixed a bug where each code snippet has an unexpected border around it. Caused by upgrading a software dependency previously (postcss-nesting). 
5-min loom video: https://www.loom.com/share/bb429959c6184c70bd32cc89c7b0d423

[W-13120528 + W-13121643] bug fixes - breadcrumbs, code snippet

---

package-lock.json
src/css/adoc/doc-footer.css
src/css/specific/nav.css
src/js/02-table-of-content.js
src/js/18-scroll-positions.js

ref: W-13285621
- revert some of the CSS changes from #402 which broke the look&feel of certain elements
- adjust scroll positions
https://www.loom.com/share/2852a873c1a748df901047002f8a88dd

[W-13285621] minor cosmetic bug fixes

---

.github/CODEOWNERS
src/css/components/select.css
src/js/02-table-of-content.js
src/js/18-scroll-positions.js

ref: W-10813710
- refactor TOC code to make it easier to maintain (and easier to unit test them in the future)
- when a keyboard user press the ENTER key to select a TOC item, adjust the focus to the anchor of that item (previously the focus was lost)
- set max height for the dropdown arrow so a client-side script doesn't add top margin to it, causing UI defect
- fix codeowner team name

[W-10813710] refactor table of content (aka right nav)

---

preview-site-src/elements/table.adoc
src/css/adoc/doc.css
src/partials/header/header-content-archive.hbs
src/partials/header/header-content-en.hbs

ref: W-13556914
fix the font size of the lists inside tables so their fonts aren't bigger than the rest.
before:
after:
also updated marketing headers.

[W-13556914] fix table list font size

---

preview-site-src/elements/table.adoc
src/js/21-coveo-facets.js
src/js/22-coveo-pager.js
src/js/vendor/coveo.bundle.js
src/partials/head/head-scripts.hbs
src/partials/header/header-content-en.hbs
src/partials/search/search-interface.hbs

ref: [W-13571346](https://gus.lightning.force.com/a07EE00001TQWbuYAH)
- upgrade atomic library v2.21 -> v2.31
- refactor out Cover pager and facet scripts to make them easier to maintain
- fix a table format in the preview site

[W-13571346] clean up Coveo code + upgrade Atomic library

---

src/partials/nav.hbs
src/partials/notice-banner/banner-latest-version-snippet.hbs

ref: W-12985536
at Open Devise's recommendation, switch to using relativize instead of site.url

[W-12985536] use relativize url

---

src/partials/survey/mobile-survey.hbs
src/partials/survey/survey.hbs

ref: [W-13667862](https://gus.lightning.force.com/a07EE00001UrSlFYAV)
update wording for the customer feedback survey banner

[W-13667862] update customer feedback survey banner wording

---

src/css/adoc/table.css
src/js/23-table.js

[W-10813725] cover 1 more edge case with callouts

---

src/partials/survey/mobile-survey.hbs

ref: W-13667862
forgot to update the number of gifts cards in the popover

[W-13667862] Update popover gift card number

---

src/css/adoc/description-list.css
src/partials/survey/mobile-survey.hbs

ref: W-12721648
old look:
new look:

[W-12721648] adjust definition list look & feel

---

src/js/21-coveo-facets.js
src/partials/head/head-scripts.hbs

ref: W-13856451
- upgrade atomic library
- change version facet sort order so newer versions show up above older versions

[W-13856451] upgrade atomic library

---

preview-site-src/index.adoc
src/css/adoc/description-list.css
src/css/highlight.css
src/css/pages/home.css
src/partials/landing-page/latest-releases.hbs
src/partials/survey/mobile-survey.hbs
src/partials/survey/survey.hbs

ref: W-12477561
used lighthouse to capture a few accessibility issues for mobile, and fix them:
- duplicate ID for the survey
- poor contrast of code snippet colors

[W-12477561] fix mobile accessibility issues

---

package-lock.json
src/layouts/maintenance.hbs
src/layouts/search-page.hbs
src/partials/head/head.hbs

[W-13593070] fix missing favicon and scripts on the search and maintenance pages

---

preview-site-src/index.adoc
src/css/pages/home.css

ref: [W-13905698](https://gus.lightning.force.com/a07EE00001XqsEfYAJ)
fix heading bug so the "More Resources" section is not showing twice in the homepage

[W-13905698] fix heading bug in homepage

---

preview-site-src/elements/table.adoc
src/css/adoc/table.css

ref: W-13907552
fix an issue where some content is not displaying correctly in a table (in either desktop or mobile screens). I switched most of the width values to `vw`s instead of % so that they adjust correctly in different screen sizes. Also added a table in the preview site for validation.

[W-13907552] fix table displays

---

.stylelintrc
preview-site-src/general/api-led-deploy.adoc
preview-site-src/general/api-led-design.adoc
preview-site-src/general/api-led-develop.adoc
preview-site-src/general/api-led-operate.adoc
preview-site-src/general/api-led-prerequisites.adoc
preview-site-src/ui-model.yml
src/css/components/pagination.css
src/css/globals/reset.css
src/css/site.css
src/partials/article/article.hbs
src/partials/head/head-links.hbs
src/partials/pagination.hbs

ref: W-12981594
add pagination to any page with page attribute `:page-pagination:`.

[W-12981594] add pagination

---

package-lock.json
package.json
src/css/adoc/doc.css
src/css/components/pagination.css
src/js/24-code-snippet-long.js
src/partials/pagination.hbs

[W-13855859] make long code snippets collapsible

---

package-lock.json
package.json
preview-site-src/elements/code-block.adoc
src/js/vendor/highlight.bundle.js

[W-13968332] downgrade highlight.js to fix callout bug

---

src/js/01-nav.js
src/partials/head/head-scripts.hbs

ref: [W-14118670](https://gus.lightning.force.com/a07EE00001aTESwYAO)
- limit Coveo User Analytics to prod site pages (including Japanese pages) only, so that we don't index beta sites
- minor refactor to the code in 01-nav.js

[W-14118670] limit coveo user analytics to prod sites only

---

src/helpers/release-notes.js

ref: [W-14110499](https://gus.lightning.force.com/a07EE00001aOlvSYAS)
- revert #537 to remove ACB
- add a check for duplicate entries so "latest releases" section will never show the same date/title combo more than once at the same time

[W-14110499] remove ACB + add duplicate check

---

preview-site-src/general/contributors.adoc
src/partials/quickstart/jared-dominguez.hbs
src/partials/quickstart/signature-entries.hbs

Onboarding tutorial
Submitting again to fix gpg signing issues.

Add self to contributors page

---

src/css/adoc/doc.css

[W-14118400] removed 16px font-size

---

src/css/components/button.css
src/css/globals/vars.css
src/css/pages/home.css
src/css/specific/nav.css
src/css/vendor/coveo.css
src/partials/landing-page/latest-releases.hbs
src/partials/landing-page/trending-topics.hbs

After the last PR #591 went out to the beta site, I did some additional testing with Clint and discovered a few areas for improvement.
Adding the following:
* Match the Trending topics link styles to the global link styles. (Missed this initially as I didn't have a Coveo key saved locally--took care of that this time.)
* Fix bug with footer size on homepage. (Removing the background dots had unintended consequences.)
* Update button styles (not just for landing page this time). I was initially cautious of affecting the feedback button styles, but after noticing that there's several topics like [this one](https://docs.mulesoft.com/general/api-led-design) that include button elements, I went ahead and updated the default button primary styles.
* Fix missing hover states.

[W-14093770] Additional One Salesforce styling changes

---

src/partials/search/search-interface.hbs

ref: W-10592972
minor fix to #597

[W-10592972] correct JP Coveo API key var name

---

preview-site-src/ui-model.yml

This PR upgrades our local preview builds to the latest version of Antora for consistency with our prod environment. Tested builds and verified output visually.

[W-14775970] Upgrade to Antora 3.1.7

---

src/js/04-feedback.js

ref: W-14867269
add a 500 ms time buffer between a "user" clicking yes/no on the feedback form and clicking the feedback "submit" button. This idea was borrowed from Tableau to prevent bot attacks.

[W-14867269] add time buffer to prevent bot attacks

---

src/partials/notice-banner/banner-latest-version-snippet.hbs

[W-14885966] comma -> period

---

src/partials/head/head-scripts.hbs

ref: W-14901641
mostly reverting [42c1735](https://github.com/mulesoft/docs-site-ui/commit/42c173505e3a2070a2e061c363d2b8b63b2ea96a), for testing if it will re-enable google analytics

[W-14901641] revert head script reorganization

---

src/js/21-coveo-facets.js

ref: W-14981249
fix bug that is causing version facet to return error when clicking the latest version.

[W-14981249] bugfix - version facet error

---

preview-site-src-jp/jp/general/index.adoc
preview-site-src/index.adoc
src/partials/landing-page/landing-page.hbs

Remove section from the homepage by request from design.
Note that the handlebars change is enough to prevent the section from displaying, but it seems like a good idea to clean up the source content file anyway, so I've submitted a PR here:
https://github.com/mulesoft/docs-general/pull/217

[W-14565886] Remove more resources section from home page

---

preview-site-src/index.adoc
src/css/vendor/coveo.css
src/js/01-nav.js
src/partials/head/head-scripts/coveo-search-scripts.hbs
src/partials/head/head-scripts/coveo-ua-script.hbs
src/partials/landing-page/trending-topics.hbs

ref: W-15035018
also upgraded Atomic version. Validated via preview site.

[W-15035018] rename "Popular Topics" to "Trending Topics"

---

src/partials/head/head-scripts.hbs

[W-15022269] add Coveo User Analytics to JP site

---

package-lock.json
package.json
src/partials/footer/footer-content-en.hbs
src/partials/header/header-content-archive.hbs
src/partials/header/header-content-en.hbs

ref: W-15795774
- Updates marketing header + footer using auto script.
- Fixes a low vulnerability
- Reverts mulesoft/docs-site-ui#708. It is a major upgrade that is not (yet) compatible with our stack

[W-15795774] update header + footer

---

package-lock.json
src/js/09-external-links.js
src/partials/landing-page/trending-topics-fallback-en.hbs
src/partials/landing-page/trending-topics-fallback-jp.hbs

ref: [W-15921470](https://gus.lightning.force.com/a07EE00001tQkKQYA0)
Hardcoding these links so that they are consistent (the current implementation's links are broken in JP site).

[W-15921470] fix fallback links

---

preview-site-src/elements/miscellaneous.adoc
src/css/adoc/collapsible-blocks.css
src/css/globals/vars.css
src/css/site.css
src/css/vendor/normalize.css
src/js/20-table.js
src/partials/footer/footer-content-jp.hbs
src/partials/header/header-content-archive.hbs
src/partials/header/header-content-en.hbs

Match Salesforce styling for accordion items, or as Asciidoc calls them, [collapsible blocks](https://docs.asciidoctor.org/asciidoc/latest/blocks/collapsible/).
**Testing**
* Tested in Chrome and Safari.
* Tested across multiple screen resolutions.
* Added example collapsible blocks to the preview site for testing.
Including a few screenshots of the output below.
Stacked blocks:
Hover styling:
Wrapped title and heading in block:

[W-15177355] Update collapsible block styling

---

gulp.d/tasks/release.js

ref: W-16084826
Fix a bug which one of the params was missing when creating a PR and it broke the script.
Revalidated via https://github.com/mulesoft/docs-site-playbook/pull/2678

[W-16084826] fix release script bug

---

gulp.d/tasks/release.js
src/css/pages/home.css
src/layouts/home.hbs
src/partials/toolbar/breadcrumbs.hbs

ref: W-16947933, https://github.com/mulesoft/docs-general/pull/274
please also review and approve https://github.com/mulesoft/docs-general/pull/274.
Add some logic to make archive site landing page compatible with home.hbs which removes the empty toolbar near the top of the homepage. The toolbar is still present in the mobile screen size of the homepage, and it is present in non-hompages (any screen size).
Also added an extra `<ol>` element to the mobile screen of the archive site homepage so that the **menu** button aligns to the left of the page rather than in the center.
Validated by exporting the build UI zip file and then build EN and archive sites with it.
release.js has no changes, it was just formatted.

[W-16947933] archive site toolbar enhancements

---

Jenkinsfile
gulp.d/tasks/release.js
package-lock.json
src/js/09-external-links.js

ref: W-17054749
- upgrade node version to v22
- simplify jenkinsfile by using functions in the shared library instead of redefining functions in the jenkinsfile
- in preparation of having a partial build, I am adding 1 more function in the external link script to check whether a link is both in a local build and contains `docs.mulesoft.com` in its href attribute. If so, then don't make it an external link. This helps a more accurate testing in the local/preview site builds

[W-17054749] partial build preparation + node upgrade + simplify jenkinsfile

---

CODEOWNERS
CODE_OF_CONDUCT.md
SECURITY.md

These files are required by SF legal for all OS software (see issue on your repo titled 'Missing Required Files')

OSS required files for transfer to SF OSS team

---

src/partials/head/head-scripts.hbs
src/partials/head/head-scripts/segment-script.hbs

We are no longer using Segment. Ran a search and replace to remove all references.

[W-17162280 Remove Segment analytics script

---

CODEOWNERS
gulp.d/tasks/release.js
package-lock.json

ref: [W-18588974](https://gus.lightning.force.com/a07EE00002EpPKdYAN)
Since we are using a service account that isn't recognized as a bot, every PR it submits requires a GUS work item ID in the title to pass the traceability check, so I am hardcoding one here.
Other changes:
- Run `npm audit fix` to fix some dependency vulnerabilities
- Update repo owner from team-docs to team-docsinfra to reflect the reality that mostly MS CX Eng team works on this repo

[W-18588974] hardcode GUS work item ID to PR titles

---

src/helpers/release-notes.js

I can't build this project, so I couldn't test my code.
But here's the start of a possible fix in case it's useful.

[W-19450758] Fix for Latest Releases using date matched release for latest rather than top of page version
